name: eventconnect-frontend
region: nyc
services:
  - name: eventconnectfe
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: yoinercastillo/EventConnect
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 80
    routes:
      - path: /
    envs:
      - key: VITE_API_BASE_URL
        value: https://eventconnect-api-8oih6.ondigitalocean.app/api
        scope: BUILD_TIME
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
